#!/bin/sh /etc/rc.common

# 16 is right after startup (15)
START=16
STOP=16

USE_PROCD=1

start_service() {
	procd_open_instance interface-watcher
	procd_set_param command /usr/bin/interface_watcher.sh
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn 3600 5 0
	procd_close_instance
}

stop_service() {
	ps | grep "/usr/bin/interface_watcher.sh" | awk '{print $1}' | xargs kill -9 "$1" 2>&1
}
