FROM debian:stretch

USER root

RUN apt-get update
RUN apt-get install -y openssh-client
RUN apt-get install -y netcat
RUN apt-get install -y curl

ENV SRC=/home/mfw/test-agent
RUN mkdir -p ${SRC}
VOLUME ${SRC}

WORKDIR ${SRC}

ENTRYPOINT [ "./test-agent.sh" ]
