#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=99
STOP=99

USE_PROCD=1

LED_TYPE_NAME=caswell:green:wifi
LED_PATH=/sys/class/leds/$LED_TYPE_NAME

boot() {
    grep -q -e caswell-caf-0262 -e untangle-inc-default-string /tmp/sysinfo/board_name
    if [ $? -eq 0 ] ; then
        echo netdev > $LED_PATH/trigger
        echo wlan0 > $LED_PATH/device_name
        echo 1 > $LED_PATH/tx
        echo 1 > $LED_PATH/rx
    fi
}

