#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=99
STOP=99

USE_PROCD=1

start_service() {
    procd_open_instance packetd

    # command
    procd_set_param command /usr/bin/packetd
    # restart indefinitely if crashed, 5 seconds between attempts
    procd_set_param respawn 3600 5 0
    # stdout to system log
    procd_set_param stdout 1
    # stderr to system log
    procd_set_param stderr 1

    procd_close_instance
}

