#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

# 21 is right after networking (20)
START=21
STOP=21

USE_PROCD=1

start_service() {
    procd_open_instance bctid

    # command
    procd_set_param command /usr/bin/bctid -c /etc/config/bcti.cfg 8484

    # stdout to system log
    procd_set_param stdout 1
    # stderr to system log
    procd_set_param stderr 1

    procd_close_instance
}

